local class = require("core.class")

local Element = class()

function Element:new()
    self.x = 1
    self.y = 1
    self.width = 10
    self.height = 1
    self.backgroundColor = colors.black
    self.foregroundColor = colors.white
    self.zIndex = 1
    self.visible = true
    
    self.draggable = false
    self.resizable = false
    
    self.parent = nil
    self.children = {}
    
    -- Callbacks
    self.onClick = nil
    self.onRightClick = nil
    self.onMiddleClick = nil
    self.onHover = nil
    self.onLeave = nil
    self.onDrag = nil
    self.onScroll = nil
    self.onKey = nil
    self.onChar = nil
    
    -- Internal state
    self._isHovered = false
    self._isDragging = false
    self._dragOffsetX = 0
    self._dragOffsetY = 0
end

function Element:addChild(child)
    table.insert(self.children, child)
    child.parent = self
end

function Element:removeChild(child)
    for i, c in ipairs(self.children) do
        if c == child then
            table.remove(self.children, i)
            child.parent = nil
            break
        end
    end
end

-- Render function to be overridden by subclasses
function Element:draw(renderTarget)
    -- Base element just draws a background rectangle if visible and dimensions are > 0
    if not self.visible then return end
    
    if self.backgroundColor and self.width > 0 and self.height > 0 then
        renderTarget.setBackgroundColor(self.backgroundColor)
        for dy = 0, self.height - 1 do
            renderTarget.setCursorPos(self.x, self.y + dy)
            renderTarget.write(string.rep(" ", self.width))
        end
    end
    
    -- Draw children (sorted by zIndex ascending so higher zIndex draws over lower)
    local sortedChildren = {}
    for _, c in ipairs(self.children) do table.insert(sortedChildren, c) end
    table.sort(sortedChildren, function(a, b) return a.zIndex < b.zIndex end)
    
    for _, c in ipairs(sortedChildren) do
        c:draw(renderTarget)
    end
end

function Element:hitTest(x, y)
    return x >= self.x and x < self.x + self.width and y >= self.y and y < self.y + self.height
end

function Element:handleEvent(event, p1, p2, p3)
    if not self.visible then return false end
    
    -- Sort children backwards to pass events to highest zIndex first
    local sortedChildren = {}
    for _, c in ipairs(self.children) do table.insert(sortedChildren, c) end
    table.sort(sortedChildren, function(a, b) return a.zIndex > b.zIndex end)
    
    for _, c in ipairs(sortedChildren) do
        if c:handleEvent(event, p1, p2, p3) then
            return true -- Event consumed by child
        end
    end
    
    -- Handle generic built-in events for self
    if event == "mouse_click" or event == "monitor_touch" then
        local button, x, y = p1, p2, p3
        if event == "monitor_touch" then button, x, y = 1, p1, p2 end
        
        if self:hitTest(x, y) then
            if self.draggable and button == 1 then
                self._isDragging = true
                self._dragOffsetX = x - self.x
                self._dragOffsetY = y - self.y
            end
            
            if button == 1 and self.onClick then self.onClick(self, x, y) end
            if button == 2 and self.onRightClick then self.onRightClick(self, x, y) end
            if button == 3 and self.onMiddleClick then self.onMiddleClick(self, x, y) end
            
            return true -- Consumed
        end
        -- if clicked outside, maybe we were hovered, drop it
        if self._isHovered then
            self._isHovered = false
            if self.onLeave then self.onLeave(self, x, y) end
        end
    elseif event == "mouse_drag" then
        local button, x, y = p1, p2, p3
        if self._isDragging then
            self.x = x - self._dragOffsetX
            self.y = y - self._dragOffsetY
            if self.onDrag then self.onDrag(self, x, y) end
            return true
        end
    elseif event == "mouse_up" then
        if self._isDragging then
            self._isDragging = false
            return true
        end
    elseif event == "mouse_scroll" then
        local dir, x, y = p1, p2, p3
        if self:hitTest(x, y) then
            if self.onScroll then self.onScroll(self, dir, x, y) end
            return true
        end
    elseif event == "mouse_move" then -- Synthetic event generated by Screen
        local x, y = p1, p2
        local hit = self:hitTest(x, y)
        if hit and not self._isHovered then
            self._isHovered = true
            if self.onHover then self.onHover(self, x, y) end
        elseif not hit and self._isHovered then
            self._isHovered = false
            if self.onLeave then self.onLeave(self, x, y) end
        end
    end
    
    if event == "key" and self.onKey then
        return self.onKey(self, p1, p2)
    end
    if event == "char" and self.onChar then
        return self.onChar(self, p1)
    end
    
    return false
end

return Element
